### ISSUE TITLE
Add argument to specify the location of dataset on the command line

### ISSUE THREAD

**Issue by gbe** [Acceis/bqm#24]
Hello,

as discussed in https://github.com/ThePorgs/Exegol-images/pull/163, could you add support so that the location of the dataset could be specified on the command line?

Thanks in advance

**Comment by noraj** [comment]
I added the option to merge local custom queries files from the CLI rather than the option to specify the dataset location.
It's more handy to specify a file directly rather than having to edit the JSON file or create a new one in a custom location.

https://github.com/Acceis/bqm/releases/tag/v1.4.0
